export interface ApplicationType {
  id: string
  name: string
  description: string
  requiredRole?: string // Discord role ID der kan se disse ansøgninger
  fields: {
    id: string
    label: string
    type: "text" | "textarea" | "number" | "select"
    placeholder?: string
    required: boolean
    options?: string[] // For select fields
    min?: number // For number fields
    rows?: number // For textarea fields
  }[]
}

export const applicationTypes: ApplicationType[] = [
   {
    id: "staff",
    name: "Staff Ansøgning",
    description: "Ansøg om at blive en staff på serveren.",
    requiredRole: "1427628590580895825", // Erstat med din Discord rolle ID
    fields: [
      {
        id: "alder",
        label: "Alder",
        type: "number",
        placeholder: "18",
        required: true,
        min: 18,
      },
      {
        id: "spilletid",
        label: "Hvor meget spilletid har du på Division?",
        type: "textarea",
        placeholder: "Hvor meget spilletid har du på Division?",
        required: true,
        rows: 1,
      },
      {
        id: "hvad_laver_du_ingame",
        label: "Hvad laver du ingame på Division?",
        type: "textarea",
        placeholder: "Fortæl os hvad du laver ingame på Division...",
        required: true,
        rows: 4,
      },
      {
        id: "hvorfor_staff",
        label: "Hvorfor vil du være en del af staff teamet hos Division?",
        type: "textarea",
        placeholder: "Fortæl os hvorfor du vil være en del af staff teamet hos Division...",
        required: true,
        rows: 10,
      },
      {
        id: "hvorfor_dig",
        label: "Hvorfor skal vi vælge dig frem for andre ansøgere?",
        type: "textarea",
        placeholder: "Fortæl os hvorfor du skal vælges frem for andre ansøgere...",
        required: true,
        rows: 10,
      },
      {
        id: "tid",
        label: "Hvor meget tid om ugen har du til at kunne hjælpe og spille på Division?",
        type: "textarea",
        placeholder: "Fortæl os hvor meget tid du kan afsætte til Division...",
        required: true,
        rows: 10,
      },
      {
        id: "tidligere_erfaring",
        label: "Har du tidligere erfaring med at være staff på en rp server? Hvis ja, hvilke?",
        type: "textarea",
        placeholder: "Fortæl os om din tidligere erfaring som staff på en rp server...",
        required: true,
        rows: 10,
      },
      {
        id: "om_dig",
        label: "Fortæl lidt om dig selv?",
        type: "textarea",
        placeholder: "Fortæl os om dig selv...",
        required: true,
        rows: 10,
      },
      {
        id: "scenarie",
        label: "Hvad ville du gøre hvis du modtog en report, omkring metagaming?",
        type: "textarea",
        placeholder: "Fortæl os hvad du ville gøre...",
        required: true,
        rows: 10,
      },
      {
        id: "scenarie",
        label: "Hvad sker der, hvis du ikke er aktiv nok som staff?",
        type: "select",
        // placeholder: "Fortæl os hvad du ville gøre...",
        required: true,
        options: [
          "Du bliver fyret som staff.",
          "Du bliver forfremmet.",
          "Du forsætter som staff selvom du er inaktivitet."
        ],
      },
    ],
  },
  {
    id: "firma",
    name: "Firma Ansøgning",
    description: "Ansøg om at blive et firma på serveren.",
    requiredRole: "1427634587135119411", // Erstat med din Discord rolle ID
    fields: [
      {
        id: "firmanavn",
        label: "Firmanavn",
        type: "textarea",
        placeholder: "Fortæl os hvad dit firmanavn er...",
        required: true,
        rows: 1,
      },
      {
        id: "firmaformål",
        label: "Hvad er formålet med virksomheden?",
        type: "textarea",
        placeholder: "Fortæl os hvad formålet med din virksomhed er...",
        required: true,
        rows: 5,
      },
      {
        id: "firmaejerskab",
        label: "Ejerskab (Procenter, hvis flere ejere)?",
        type: "textarea",
        placeholder: "Fortæl os om ejerskabet af virksomheden...",
        required: true,
        rows: 5,
      },
      {
        id: "hvordan_tjener_virksomheden_penge",
        label: "Hvordan tjener virksomheden penge - Omsætning og omkostninger?",
        type: "textarea",
        placeholder: "Fortæl os om virksomhedens omsætning og omkostninger...",
        required: true,
        rows: 5,
      },
      {
        id: "hvad_kræver_virksomheden_af_udviklerne",
        label: "Hvad kræver virksomheden af udviklerne (Script, MLO, osv.)?",
        type: "textarea",
        placeholder: "Fortæl os hvad virksomheden kræver af udviklerne...",
        required: true,
        rows: 10,
      },
      {
        id: "startkapital",
        label: "Hvor meget startkapital har du til at starte virksomheden?",
        type: "textarea",
        placeholder: "Fortæl os hvor meget startkapital du har...",
        required: true,
        rows: 5,
      },
      {
        id: "medarbejdere_oversigt",
        label: "Medarbejdere oversigt (Discord, ingame navn, alder & steam link inkluderet)?",
        type: "textarea",
        placeholder: "grisenw - Abdi Hassan - 31 - steamlink",
        required: true,
        rows: 30,
      },
    ],
  },
    {
    id: "cc",
    name: "Content Creator Ansøgning",
    description: "Ansøg om at blive en del af vores content creator team",
    requiredRole: "1427634628742615171", // Erstat med din Discord rolle ID
    fields: [
      {
        id: "alder",
        label: "Alder",
        type: "number",
        placeholder: "18",
        required: true,
        min: 18,
      },
      {
        id: "creator_navn",
        label: "Hvad er dit creator navn?",
        type: "textarea",
        placeholder: "Angiv dit creator navn...",
        required: true,
        rows: 1,
      },
      {
        id: "creator_platform",
        label: "Hvilken platform laver du content på?",
        type: "textarea",
        placeholder: "Angiv hvilken platform du laver content på...",
        required: true,
        rows: 5,
      },
      {
        id: "antal_folgere",
        label: "Hvor mange følgere har du?",
        type: "textarea",
        placeholder: "Angiv hvor mange følgere du har...",
        required: true,
        rows: 5,
      },
      {
        id: "gennemsnitlige_seere",
        label: "Såfremt du streamer, hvor mange gennemsnitlige seere har du?",
        type: "textarea",
        placeholder: "Angiv hvor mange gennemsnitlige seere du har...",
        required: true,
        rows: 5,
      },
      {
        id: "hvor_ofte_laver_du_content",
        label: "Hvor ofte laver du content?",
        type: "textarea",
        placeholder: "Angiv hvor ofte du laver content...",
        required: true,
        rows: 5,
      },
      {
        id: "link",
        label: "Link til din platform?",
        type: "textarea",
        placeholder: "Angiv linket til din platform...",
        required: true,
        rows: 5,
      },
    ],
  },
  {
    id: "Betatester",
    name: "Beta Tester Ansøgning",
    description: "Ansøg om at blive en del af vores beta tester team",
    // Ingen requiredRole - alle med admin adgang kan se beta tester ansøgninger
    fields: [
      {
        id: "age",
        label: "Alder",
        type: "number",
        placeholder: "18",
        required: true,
        min: 18,
      },
      {
        id: "hvorfor_dig",
        label: "Hvorfor dig?",
        type: "textarea",
        placeholder: "Fortæl os hvorfor vi skal vælge netop dig...",
        required: true,
        rows: 5,
      },
      {
        id: "aktivitet",
        label: "Hvor aktiv kan du være?",
        type: "textarea",
        placeholder: "Fortæl os hvor aktiv du kan være...",
        required: true,
        rows: 1,
      },
    ],
  },
    {
    id: "bande",
    name: "Bande Ansøgning",
    description: "Ansøg om at blive en bande på serveren.",
    requiredRole: "1427634558718971974", // Erstat med din Discord rolle ID
    fields: [
      {
        id: "hvor_kan_bande_regler_findes",
        label: "Hvor kan Division bande regelsæt findes?",
        type: "textarea",
        placeholder: "Fortæl os hvor du kan finde Division bande regelsæt...",
        required: true,
        rows: 1,
      },
      {
        id: "bande_navn",
        label: "Navn på banden?",
        type: "textarea",
        placeholder: "Fortæl os navnet på din bande...",
        required: true,
        rows: 1,
      },
      {
        id: "medlemsliste",
        label: "Medlemsliste (Discord, ingame navn, alder & steam link inkluderet)?",
        type: "textarea",
        placeholder: "grisenw - Abdi Hassan - 31 - steamlink",
        required: true,
        rows: 25,
      },
      {
        id: "baggrund",
        label: "En baggrund for jeres bande, hvordan er den opstået og hvad er jeres formål?",
        type: "textarea",
        placeholder: "Giv os en baggrund for jeres bande...",
        required: true,
        rows: 10,
      },
      {
        id: "rekrutterings_beskrivelse",
        label: "Beskrivelse på hvordan i rekruttere nye medlemmer?",
        type: "textarea",
        placeholder: "Giv os en beskrivelse på hvordan i rekruttere nye medlemmer...",
        required: true,
        rows: 10,
      },
      {
        id: "lokation",
        label: "Hvilken lokation har jeres bande lyst til at opkøbe som bande grund?",
        type: "textarea",
        placeholder: "Hvis I ønsker at benytte billede til at beskrive jeres lokation, så upload det til en billede hjemmeside, såsom Imgur eller Gyazo og så del linket nedenfor.",
        required: true,
        rows: 5,
      },
      {
        id: "dresscode",
        label: "Har I en bestemt dresscode?",
        type: "textarea",
        placeholder: "Hvis I ønsker at benytte billede til at beskrive jeres dresscode, så upload det til en billede hjemmeside, såsom Imgur eller Gyazo og så del linket nedenfor.",
        required: true,
        rows: 5,
      },
    ],
  },
  {
    id: "wlmodtager",
    name: "Whitelist Modtager",
    description: "Ansøg om at blive whitelist modtager",
    requiredRole: "1427634524673544232", // Erstat med din Discord rolle ID
    fields: [
      {
        id: "alder",
        label: "Alder?",
        type: "number",
        placeholder: "18",
        required: true,
        min: 18,
      },
      {
        id: "steam_link",
        label: "Steam Link?",
        type: "textarea",
        placeholder: "Angiv dit steam link.",
        required: true,
        rows: 1,
      },
      {
        id: "tidligere_erfaring",
        label: "Tidligere Erfaring?",
        type: "textarea",
        placeholder: "Angiv din tidligere erfaring.",
        required: true,
        rows: 10,
      },
      {
        id: "hvorfor_whitelist",
        label: "Hvorfor vil du gerne være en del af whitelist teamet?",
        type: "textarea",
        placeholder: "Fortæl os hvorfor du vil være en del af whitelist teamet.",
        required: true,
        rows: 10,
      },
      {
        id: "opgave",
        label: "Hvad er din opgave som whitelist modtager?",
        type: "textarea",
        placeholder: "Angiv din opgave som whitelist modtager.",
        required: true,
        rows: 10,
      },
      {
        id: "bidrag",
        label: "Hvordan kan du bidrage til teamet?",
        type: "textarea",
        placeholder: "Angiv hvordan du kan bidrage til teamet.",
        required: true,
        rows: 10,
      },
      {
        id: "samtale_håndtering",
        label: "Hvordan håndterer du en whitelist samtale, og hvad ligger du vægt på under samtalen?",
        type: "textarea",
        placeholder: "Angiv hvordan du håndterer en whitelist samtale.",
        required: true,
        rows: 10,
      },
      {
        id: "aktivitet",
        label: "Hvor aktiv forventer du at være på serveren?",
        type: "select",
        // placeholder: "Angiv hvor aktiv du forventer at være på serveren.",
        required: true,
        options: [
          "Meget aktiv (flere gange om ugen)",
          "Moderat aktiv (et par gange om ugen)",
          "Sjældent aktiv (en gang om ugen)",
        ],
        // rows: 10,
      },
      {
        id: "regelment",
        label: "Har du forstået vores regelment?",
        type: "select",
        // placeholder: "Angiv hvor aktiv du forventer at være på serveren.",
        required: true,
        options: [
          "Ja",
          "Nej",
        ],
        // rows: 10,
      },
      {
        id: "bemærkninger",
        label: "Nogen ekstra bemærkninger som vi skal tage hensyn til (Skriftlige udfordringer eller andet)?",
        type: "textarea",
        placeholder: "Angiv dine bemærkninger, hvis du har nogen.",
        required: false,
        rows: 10,
      },
    ],
  },
  {
    id: "whitelist",
    name: "Whitelist Ansøgning", 
    description: "Ansøg om whitelist til serveren",
    // Specificer rollerne der kan se whitelist ansøgninger - du kan tilføje flere roller her
    requiredRole: "1422323250339250206", // Start med basic whitelisted rolle
    fields: [
      {
        id: "alder",
        label: "IRL Alder",
        type: "number",
        placeholder: "18",
        required: true,
        min: 18,
      },
      {
        id: "karakter_navn",
        label: "Karakter Navn",
        type: "textarea",
        placeholder: "Vekå Larsen",
        required: true,
      },
      {
        id: "karakter_alder",
        label: "Karakterens Alder",
        type: "number",
        placeholder: "18",
        required: true,
        min: 18,
      },
      {
        id: "hvorfor_division",
        label: "Hvorfor ansøger du til Division?",
        type: "textarea",
        placeholder: "Fortæl os hvorfor du ansøger til Division...",
        required: true,
        rows: 6,
      },
      {
        id: "timer_og_servere",
        label: "FiveM timer & servere",
        type: "textarea",
        placeholder: "Skriv antal timer og servere",
        required: true,
        rows: 3,
      },
    ],
  },
]
